use std::fmt::Write;
use crate::ast::*;
use crate::error::{MinusError, Result};

pub struct CodeGenerator {
    output: String,
    temp_counter: usize,
    label_counter: usize,
    strings: Vec<String>,
    current_function: Option<String>,
}

impl CodeGenerator {
    pub fn new() -> Self {
        CodeGenerator {
            output: String::new(),
            temp_counter: 0,
            label_counter: 0,
            strings: Vec::new(),
            current_function: None,
        }
    }

    pub fn generate(&mut self, program: &Program) -> Result<String> {
        // Add standard library declarations
        write!(self.output, "; Generated by minus compiler\n").unwrap();
        write!(self.output, "target datalayout = \"e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128\"\n").unwrap();
        write!(self.output, "target triple = \"x86_64-apple-darwin\"\n").unwrap();
        write!(self.output, "\n").unwrap();

        // External declarations
        write!(self.output, "@.str = private unnamed_addr constant [4 x i8] c\"%%d\\0A\\00\"\n").unwrap();
        write!(self.output, "@.str.1 = private unnamed_addr constant [4 x i8] c\"%%f\\0A\\00\"\n").unwrap();
        write!(self.output, "@.str.2 = private unnamed_addr constant [4 x i8] c\"%%s\\0A\\00\"\n").unwrap();
        write!(self.output, "@.str.3 = private unnamed_addr constant [4 x i8] c\"%%c\\0A\\00\"\n").unwrap();
        write!(self.output, "\n").unwrap();

        // External function declarations
        write!(self.output, "declare i32 @printf(i8*, ...)\n").unwrap();
        write!(self.output, "declare i8* @malloc(i64)\n").unwrap();
        write!(self.output, "declare void @free(i8*)\n").unwrap();
        write!(self.output, "declare i64 @strlen(i8*)\n").unwrap();
        write!(self.output, "declare i8* @strcpy(i8*, i8*)\n").unwrap();
        write!(self.output, "declare i8* @strcat(i8*, i8*)\n").unwrap();
        write!(self.output, "\n").unwrap();

        // Generate function definitions
        for item in &program.items {
            match item {
                Item::Function(func) => self.generate_function(func)?,
                Item::Struct(_) => {
                    // Structs are handled as named types in LLVM
                }
                Item::Import(_) => {
                    // Imports are handled at a higher level
                }
            }
        }

        // Add string constants
        for (i, s) in self.strings.iter().enumerate() {
            let escaped = s.replace('\\', "\\\\")
                .replace('"', "\\\"")
                .replace('\n', "\\0A")
                .replace('\t', "\\09")
                .replace('\0', "\\00");
            writeln!(
                self.output,
                "@.str.{} = private unnamed_addr constant [{} x i8] c\"{}\\00\"",
                i + 10,
                s.len() + 1,
                escaped
            )
            .unwrap();
        }

        Ok(self.output.clone())
    }

    fn generate_function(&mut self, func: &FunctionDef) -> Result<()> {
        self.current_function = Some(func.name.clone());
        self.temp_counter = 0;
        self.label_counter = 0;

        let return_type = self.llvm_type(&func.return_type);
        let params: Vec<String> = func
            .params
            .iter()
            .map(|p| format!("{} %{}", self.llvm_type(&p.param_type), p.name))
            .collect();

        writeln!(
            self.output,
            "define {} @{}({}) {{",
            return_type,
            func.name,
            params.join(", ")
        )
        .unwrap();

        // Entry block
        writeln!(self.output, "entry:").unwrap();

        // Allocate parameters
        for param in &func.params {
            let alloca = self.next_temp();
            writeln!(
                self.output,
                "  {} = alloca {}",
                alloca,
                self.llvm_type(&param.param_type)
            )
            .unwrap();
            writeln!(
                self.output,
                "  store {} %{}, {}* {}",
                self.llvm_type(&param.param_type),
                param.name,
                self.llvm_type(&param.param_type),
                alloca
            )
            .unwrap();
        }

        // Generate body
        self.generate_block(&func.body)?;

        // Add implicit return for void functions
        if func.return_type == Type::Void {
            writeln!(self.output, "  ret void").unwrap();
        }

        writeln!(self.output, "}}").unwrap();
        writeln!(self.output).unwrap();

        Ok(())
    }

    fn generate_block(&mut self, block: &Block) -> Result<()> {
        for stmt in &block.statements {
            self.generate_statement(stmt)?;
        }
        Ok(())
    }

    fn generate_statement(&mut self, stmt: &Statement) -> Result<()> {
        match stmt {
            Statement::VariableDecl {
                var_type,
                name: _,
                initializer,
                ..
            } => {
                let alloca = self.next_temp();
                writeln!(
                    self.output,
                    "  {} = alloca {}",
                    alloca,
                    self.llvm_type(var_type)
                )
                .unwrap();

                if let Some(init) = initializer {
                    let value = self.generate_expression(init)?;
                    writeln!(
                        self.output,
                        "  store {} {}, {}* {}",
                        self.llvm_type(var_type),
                        value,
                        self.llvm_type(var_type),
                        alloca
                    )
                    .unwrap();
                }
            }
            Statement::Assignment { target, value, .. } => {
                let target_ptr = self.generate_expression_address(target)?;
                let value = self.generate_expression(value)?;
                let ty = self.get_expression_type(target);
                writeln!(
                    self.output,
                    "  store {} {}, {}* {}",
                    self.llvm_type(&ty),
                    value,
                    self.llvm_type(&ty),
                    target_ptr
                )
                .unwrap();
            }
            Statement::ExpressionStmt { expr, .. } => {
                self.generate_expression(expr)?;
            }
            Statement::If {
                condition,
                then_block,
                else_block,
                ..
            } => {
                let cond = self.generate_expression(condition)?;
                let then_label = self.next_label();
                let else_label = self.next_label();
                let end_label = self.next_label();

                writeln!(
                    self.output,
                    "  br i1 {}, label %{}, label %{}",
                    cond, then_label, else_label
                )
                .unwrap();

                writeln!(self.output, "{}:", then_label).unwrap();
                self.generate_block(then_block)?;
                writeln!(self.output, "  br label %{}", end_label).unwrap();

                writeln!(self.output, "{}:", else_label).unwrap();
                if let Some(else_clause) = else_block {
                    match else_clause {
                        ElseClause::Block(block) => self.generate_block(block)?,
                        ElseClause::If { .. } => {
                            // Handle else if
                        }
                    }
                }
                writeln!(self.output, "  br label %{}", end_label).unwrap();

                writeln!(self.output, "{}:", end_label).unwrap();
            }
            Statement::While {
                condition, body, ..
            } => {
                let cond_label = self.next_label();
                let body_label = self.next_label();
                let end_label = self.next_label();

                writeln!(self.output, "  br label %{}", cond_label).unwrap();
                writeln!(self.output, "{}:", cond_label).unwrap();

                let cond = self.generate_expression(condition)?;
                writeln!(
                    self.output,
                    "  br i1 {}, label %{}, label %{}",
                    cond, body_label, end_label
                )
                .unwrap();

                writeln!(self.output, "{}:", body_label).unwrap();
                self.generate_block(body)?;
                writeln!(self.output, "  br label %{}", cond_label).unwrap();

                writeln!(self.output, "{}:", end_label).unwrap();
            }
            Statement::For {
                init,
                condition,
                update,
                body,
                ..
            } => {
                if let Some(init_stmt) = init {
                    self.generate_statement(init_stmt)?;
                }

                let cond_label = self.next_label();
                let body_label = self.next_label();
                let update_label = self.next_label();
                let end_label = self.next_label();

                writeln!(self.output, "  br label %{}", cond_label).unwrap();
                writeln!(self.output, "{}:", cond_label).unwrap();

                if let Some(cond) = condition {
                    let cond_val = self.generate_expression(cond)?;
                    writeln!(
                        self.output,
                        "  br i1 {}, label %{}, label %{}",
                        cond_val, body_label, end_label
                    )
                    .unwrap();
                } else {
                    writeln!(self.output, "  br label %{}", body_label).unwrap();
                }

                writeln!(self.output, "{}:", body_label).unwrap();
                self.generate_block(body)?;
                writeln!(self.output, "  br label %{}", update_label).unwrap();

                writeln!(self.output, "{}:", update_label).unwrap();
                if let Some(update_stmt) = update {
                    self.generate_statement(update_stmt)?;
                }
                writeln!(self.output, "  br label %{}", cond_label).unwrap();

                writeln!(self.output, "{}:", end_label).unwrap();
            }
            Statement::Switch {
                expression,
                cases,
                default_case,
                ..
            } => {
                let switch_val = self.generate_expression(expression)?;
                let end_label = self.next_label();

                // Generate case labels
                let case_labels: Vec<(String, String)> = cases
                    .iter()
                    .map(|_| (self.next_temp(), self.next_label()))
                    .collect();

                let default_label = if default_case.is_some() {
                    self.next_label()
                } else {
                    end_label.clone()
                };

                // Generate switch instruction
                writeln!(
                    self.output,
                    "  switch i32 {}, label %{} [",
                    switch_val, default_label
                )
                .unwrap();

                for (case, (_, label)) in cases.iter().zip(case_labels.iter()) {
                    if let Expression::IntLiteral(val) = &case.value {
                        writeln!(self.output, "    i32 {}, label %{}", val, label).unwrap();
                    }
                }

                writeln!(self.output, "  ]").unwrap();

                // Generate case bodies
                for (case, (_, label)) in cases.iter().zip(case_labels.iter()) {
                    writeln!(self.output, "{}:", label).unwrap();
                    self.generate_block(&case.body)?;
                    writeln!(self.output, "  br label %{}", end_label).unwrap();
                }

                if let Some(default) = default_case {
                    writeln!(self.output, "{}:", default_label).unwrap();
                    self.generate_block(default)?;
                    writeln!(self.output, "  br label %{}", end_label).unwrap();
                }

                writeln!(self.output, "{}:", end_label).unwrap();
            }
            Statement::Return { value, .. } => {
                if let Some(return_value) = value {
                    let val = self.generate_expression(return_value)?;
                    let ty = self.get_expression_type(return_value);
                    writeln!(self.output, "  ret {} {}", self.llvm_type(&ty), val).unwrap();
                } else {
                    writeln!(self.output, "  ret void").unwrap();
                }
            }
            Statement::Break { .. } => {
                // Break is handled by generating a jump to the loop exit
                writeln!(self.output, "  br label %break_label").unwrap();
            }
            Statement::Continue { .. } => {
                // Continue is handled by generating a jump to the loop condition
                writeln!(self.output, "  br label %continue_label").unwrap();
            }
        }

        Ok(())
    }

    fn generate_expression(&mut self, expr: &Expression) -> Result<String> {
        match expr {
            Expression::IntLiteral(value) => Ok(format!("i32 {}", value)),
            Expression::FloatLiteral(value) => Ok(format!("double {}", value)),
            Expression::StringLiteral(value) => {
                let idx = self.strings.len();
                self.strings.push(value.clone());
                Ok(format!(
                    "getelementptr inbounds ([{} x i8], [{} x i8]* @.str.{}, i32 0, i32 0)",
                    value.len() + 1,
                    value.len() + 1,
                    idx + 10
                ))
            }
            Expression::CharLiteral(value) => Ok(format!("i32 {}", *value as i32)),
            Expression::BoolLiteral(value) => Ok(format!("i1 {}", if *value { 1 } else { 0 })),
            Expression::Identifier(name) => {
                let alloca = self.find_variable(name)?;
                let ty = self.get_variable_type(name);
                let temp = self.next_temp();
                writeln!(
                    self.output,
                    "  {} = load {}, {}* {}",
                    temp,
                    self.llvm_type(&ty),
                    self.llvm_type(&ty),
                    alloca
                )
                .unwrap();
                Ok(temp)
            }
            Expression::BinaryOp { op, left, right } => {
                let left_val = self.generate_expression(left)?;
                let right_val = self.generate_expression(right)?;
                let left_type = self.get_expression_type(left);

                match op {
                    BinaryOp::Add => {
                        let temp = self.next_temp();
                        if left_type == Type::Float {
                            writeln!(
                                self.output,
                                "  {} = fadd double {}, {}",
                                temp, left_val, right_val
                            )
                            .unwrap();
                        } else {
                            writeln!(
                                self.output,
                                "  {} = add i32 {}, {}",
                                temp, left_val, right_val
                            )
                            .unwrap();
                        }
                        Ok(temp)
                    }
                    BinaryOp::Subtract => {
                        let temp = self.next_temp();
                        if left_type == Type::Float {
                            writeln!(
                                self.output,
                                "  {} = fsub double {}, {}",
                                temp, left_val, right_val
                            )
                            .unwrap();
                        } else {
                            writeln!(
                                self.output,
                                "  {} = sub i32 {}, {}",
                                temp, left_val, right_val
                            )
                            .unwrap();
                        }
                        Ok(temp)
                    }
                    BinaryOp::Multiply => {
                        let temp = self.next_temp();
                        if left_type == Type::Float {
                            writeln!(
                                self.output,
                                "  {} = fmul double {}, {}",
                                temp, left_val, right_val
                            )
                            .unwrap();
                        } else {
                            writeln!(
                                self.output,
                                "  {} = mul i32 {}, {}",
                                temp, left_val, right_val
                            )
                            .unwrap();
                        }
                        Ok(temp)
                    }
                    BinaryOp::Divide => {
                        let temp = self.next_temp();
                        if left_type == Type::Float {
                            writeln!(
                                self.output,
                                "  {} = fdiv double {}, {}",
                                temp, left_val, right_val
                            )
                            .unwrap();
                        } else {
                            writeln!(
                                self.output,
                                "  {} = sdiv i32 {}, {}",
                                temp, left_val, right_val
                            )
                            .unwrap();
                        }
                        Ok(temp)
                    }
                    BinaryOp::Modulo => {
                        let temp = self.next_temp();
                        writeln!(
                            self.output,
                            "  {} = srem i32 {}, {}",
                            temp, left_val, right_val
                        )
                        .unwrap();
                        Ok(temp)
                    }
                    BinaryOp::Equal => {
                        let temp = self.next_temp();
                        if left_type == Type::Float {
                            writeln!(
                                self.output,
                                "  {} = fcmp oeq double {}, {}",
                                temp, left_val, right_val
                            )
                            .unwrap();
                        } else {
                            writeln!(
                                self.output,
                                "  {} = icmp eq i32 {}, {}",
                                temp, left_val, right_val
                            )
                            .unwrap();
                        }
                        Ok(temp)
                    }
                    BinaryOp::NotEqual => {
                        let temp = self.next_temp();
                        if left_type == Type::Float {
                            writeln!(
                                self.output,
                                "  {} = fcmp one double {}, {}",
                                temp, left_val, right_val
                            )
                            .unwrap();
                        } else {
                            writeln!(
                                self.output,
                                "  {} = icmp ne i32 {}, {}",
                                temp, left_val, right_val
                            )
                            .unwrap();
                        }
                        Ok(temp)
                    }
                    BinaryOp::Less => {
                        let temp = self.next_temp();
                        if left_type == Type::Float {
                            writeln!(
                                self.output,
                                "  {} = fcmp olt double {}, {}",
                                temp, left_val, right_val
                            )
                            .unwrap();
                        } else {
                            writeln!(
                                self.output,
                                "  {} = icmp slt i32 {}, {}",
                                temp, left_val, right_val
                            )
                            .unwrap();
                        }
                        Ok(temp)
                    }
                    BinaryOp::Greater => {
                        let temp = self.next_temp();
                        if left_type == Type::Float {
                            writeln!(
                                self.output,
                                "  {} = fcmp ogt double {}, {}",
                                temp, left_val, right_val
                            )
                            .unwrap();
                        } else {
                            writeln!(
                                self.output,
                                "  {} = icmp sgt i32 {}, {}",
                                temp, left_val, right_val
                            )
                            .unwrap();
                        }
                        Ok(temp)
                    }
                    BinaryOp::LessEqual => {
                        let temp = self.next_temp();
                        if left_type == Type::Float {
                            writeln!(
                                self.output,
                                "  {} = fcmp ole double {}, {}",
                                temp, left_val, right_val
                            )
                            .unwrap();
                        } else {
                            writeln!(
                                self.output,
                                "  {} = icmp sle i32 {}, {}",
                                temp, left_val, right_val
                            )
                            .unwrap();
                        }
                        Ok(temp)
                    }
                    BinaryOp::GreaterEqual => {
                        let temp = self.next_temp();
                        if left_type == Type::Float {
                            writeln!(
                                self.output,
                                "  {} = fcmp oge double {}, {}",
                                temp, left_val, right_val
                            )
                            .unwrap();
                        } else {
                            writeln!(
                                self.output,
                                "  {} = icmp sge i32 {}, {}",
                                temp, left_val, right_val
                            )
                            .unwrap();
                        }
                        Ok(temp)
                    }
                    BinaryOp::And => {
                        let temp = self.next_temp();
                        writeln!(
                            self.output,
                            "  {} = and i1 {}, {}",
                            temp, left_val, right_val
                        )
                        .unwrap();
                        Ok(temp)
                    }
                    BinaryOp::Or => {
                        let temp = self.next_temp();
                        writeln!(
                            self.output,
                            "  {} = or i1 {}, {}",
                            temp, left_val, right_val
                        )
                        .unwrap();
                        Ok(temp)
                    }
                }
            }
            Expression::UnaryOp { op, expr } => {
                let val = self.generate_expression(expr)?;
                let ty = self.get_expression_type(expr);

                match op {
                    UnaryOp::Negate => {
                        let temp = self.next_temp();
                        if ty == Type::Float {
                            writeln!(
                                self.output,
                                "  {} = fneg double {}",
                                temp, val
                            )
                            .unwrap();
                        } else {
                            writeln!(
                                self.output,
                                "  {} = sub i32 0, {}",
                                temp, val
                            )
                            .unwrap();
                        }
                        Ok(temp)
                    }
                    UnaryOp::Not => {
                        let temp = self.next_temp();
                        writeln!(
                            self.output,
                            "  {} = xor i1 {}, true",
                            temp, val
                        )
                        .unwrap();
                        Ok(temp)
                    }
                }
            }
            Expression::FunctionCall { name, args } => {
                let mut arg_vals = Vec::new();
                let mut arg_types = Vec::new();

                for arg in args {
                    let val = self.generate_expression(arg)?;
                    let ty = self.get_expression_type(arg);
                    arg_vals.push(val);
                    arg_types.push(ty);
                }

                // Handle built-in Print function
                if name == "Print" {
                    if let Some(first_arg) = args.first() {
                        let ty = self.get_expression_type(first_arg);
                        let format_str = match &ty {
                            Type::Int => "@.str",
                            Type::Float => "@.str.1",
                            Type::String => "@.str.2",
                            Type::Char => "@.str.3",
                            _ => "@.str",
                        };

                        let temp = self.next_temp();
                        writeln!(
                            self.output,
                            "  {} = call i32 (i8*, ...) @printf(i8* {}, {})",
                            temp,
                            format_str,
                            arg_vals.join(", ")
                        )
                        .unwrap();
                        return Ok(temp);
                    }
                }

                let temp = self.next_temp();
                writeln!(
                    self.output,
                    "  {} = call {} @{}({})",
                    temp,
                    self.llvm_type(&self.get_function_return_type(name)),
                    name,
                    arg_vals
                        .iter()
                        .zip(arg_types.iter())
                        .map(|(v, t)| format!("{} {}", self.llvm_type(t), v))
                        .collect::<Vec<_>>()
                        .join(", ")
                )
                .unwrap();
                Ok(temp)
            }
            Expression::MethodCall { .. } => {
                // Method calls are simplified for now
                Ok("i32 0".to_string())
            }
            Expression::FieldAccess { .. } => {
                // Field access is simplified for now
                Ok("i32 0".to_string())
            }
            Expression::ArrayAccess { .. } => {
                // Array access is simplified for now
                Ok("i32 0".to_string())
            }
            Expression::StructConstruction { .. } => {
                // Struct construction is simplified for now
                Ok("i32 0".to_string())
            }
            Expression::OkExpr(expr) => self.generate_expression(expr),
            Expression::ErrorExpr(expr) => self.generate_expression(expr),
            Expression::StringInterpolation { parts } => {
                // Simplified: just return the first text part
                if let Some(StringPart::Text(text)) = parts.first() {
                    let idx = self.strings.len();
                    self.strings.push(text.clone());
                    Ok(format!(
                        "getelementptr inbounds ([{} x i8], [{} x i8]* @.str.{}, i32 0, i32 0)",
                        text.len() + 1,
                        text.len() + 1,
                        idx + 10
                    ))
                } else {
                    Ok("i32 0".to_string())
                }
            }
            Expression::Parenthesized(expr) => self.generate_expression(expr),
            Expression::Assignment { target, value } => {
                let target_ptr = self.generate_expression_address(target)?;
                let val = self.generate_expression(value)?;
                let ty = self.get_expression_type(target);
                writeln!(
                    self.output,
                    "  store {} {}, {}* {}",
                    self.llvm_type(&ty),
                    val,
                    self.llvm_type(&ty),
                    target_ptr
                )
                .unwrap();
                Ok(val)
            }
        }
    }

    fn generate_expression_address(&mut self, expr: &Expression) -> Result<String> {
        match expr {
            Expression::Identifier(name) => self.find_variable(name),
            _ => Err(MinusError::CodegenError {
                message: "Invalid assignment target".to_string(),
            }),
        }
    }

    fn llvm_type(&self, ty: &Type) -> String {
        match ty {
            Type::Int => "i32".to_string(),
            Type::Float => "double".to_string(),
            Type::Char => "i8".to_string(),
            Type::Bool => "i1".to_string(),
            Type::String => "i8*".to_string(),
            Type::Void => "void".to_string(),
            Type::Struct(_) => "i8*".to_string(),
            Type::Result { .. } => "i8*".to_string(),
            Type::Array { .. } => "i8*".to_string(),
            Type::Pointer(_) => "i8*".to_string(),
        }
    }

    fn next_temp(&mut self) -> String {
        let temp = format!("%t{}", self.temp_counter);
        self.temp_counter += 1;
        temp
    }

    fn next_label(&mut self) -> String {
        let label = format!("label{}", self.label_counter);
        self.label_counter += 1;
        label
    }

    fn find_variable(&self, _name: &str) -> Result<String> {
        // Simplified: return a placeholder
        Ok(format!("%{}", _name))
    }

    fn get_variable_type(&self, _name: &str) -> Type {
        Type::Int
    }

    fn get_expression_type(&self, _expr: &Expression) -> Type {
        Type::Int
    }

    fn get_function_return_type(&self, _name: &str) -> Type {
        Type::Void
    }
}
